G3SpiritsReports.UI/Controllers/HomeController.cs
using G3SpiritsReports.BusinessLogic.Countries;
using G3SpiritsReports.BusinessLogic.MonthlyBrandReports;
using G3SpiritsReports.BusinessLogic.MonthlyReports;
using G3SpiritsReports.BusinessLogic.YearlyBrandReports;
using G3SpiritsReports.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace G3SpiritsReports.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly CountryManager _countryManager = new CountryManager();
        private readonly MonthlyBrandReportManager _monthlyBrandReportManager = new MonthlyBrandReportManager();
        private readonly MonthlyReportManager _monthlyReportManager = new MonthlyReportManager();
        private readonly YearlyBrandReportManager _yearlyBrandReportManager = new YearlyBrandReportManager();
        public ActionResult Index()
        {
            var countries = _countryManager.GetAllCountries();

            return View(countries);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult CountryReport()
        {
            var countryId = Convert.ToInt32(Request.QueryString["countryId"]);
            if (countryId == 0)
            {
                countryId = 1;
            }

            var dateQs = Request.QueryString["date"];
            
            var date = DateTime.Today;
            if (dateQs != "")
            {
                date = Convert.ToDateTime(Request.QueryString["date"]);
            }
            else 
            {
                var latestMonthlyBrandReport = _monthlyBrandReportManager.GetLatestMonthlyBrandReport();
                if (latestMonthlyBrandReport != null)
                    date = latestMonthlyBrandReport.Date;
            }
            var monthlyBrandReportTable = _monthlyBrandReportManager.GetMonthlyBrandReportTable(date, countryId);
            var monthlyReportTable = _monthlyReportManager.GetMonthlyReportTable(date, countryId);
            var yearlyBrandReportTable = _yearlyBrandReportManager.GetYearlyBrandReportTables(date, countryId);
            var reportTableViewModel = new ReportTableViewModel()
            {
                MonthlyBrandReportTables = monthlyBrandReportTable,
                MonthlyReportTable = monthlyReportTable,
                YearlyBrandReportTables = yearlyBrandReportTable,
                Date = date.ToShortDateString()
            };
            return View("_Report", reportTableViewModel);
        }

        public ActionResult Report()
        {
            ViewBag.Message = "Your contact page.";

            return View("_Report");
        }
    }
}

G3SpiritsReports.UI/Controllers/MonthlyBrandReportController.cs
using G3SpiritsReports.BusinessLogic.MonthlyBrandReports;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace G3SpiritsReports.UI.Controllers
{
    [Authorize]
    public class MonthlyBrandReportController : Controller
    {
        //
        // GET: /MonthlyBrandReport/
        private readonly MonthlyBrandReportManager _monthlyBrandReportManager = new MonthlyBrandReportManager();
        public ActionResult Index()
        {
            var countryId = Convert.ToInt32(Request.QueryString["countryId"]);
            if (countryId == 0)
            {
                countryId = 1;
            }
            var date = Convert.ToDateTime(Request.QueryString["date"]);
            if (date == DateTime.MinValue)
            {
                date = DateTime.Today;
            }
            
            var monthlyBrandReportHandler = _monthlyBrandReportManager.GetMonthlyBrandReport(countryId, date);
            return View(monthlyBrandReportHandler);
        }

        

        //
        // POST: /MonthlyBrandReport/Create

        [HttpGet]
        public string CreateOrEdit(int countryId, DateTime date, int brandId , int soldPieces)
        {
            try
            {
                _monthlyBrandReportManager.CreateOrEdit(countryId, date, brandId, soldPieces);
                return "OK";
            }
            catch(Exception ex)
            {
                return ex.Message;
            }
        }
    }
}

G3SpiritsReports.UI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

G3SpiritsReports.UI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

G3SpiritsReports.UI/Views/Home/Index.cshtml
@model IEnumerable<G3SpiritsReports.Models.Models.Country>
@{
    ViewBag.Title = "Home Page";
}
<div id="tabs">
    <ul>
        @{ var i = 0;}
    @foreach (var item in Model)
    {
        //if (i == 0) {
        <li><a href="#@item.Name" id="@item.CountryId">@item.Name</a></li>
        //}
        //i++;
    }
</ul>

@foreach (var item in Model)
{
    <div id="@item.Name" style="padding:1em 0.4em"></div>
}
</div>
@Scripts.Render("~/bundles/jqueryui")
@Scripts.Render("~/bundles/home")

G3SpiritsReports.UI/Views/Home/_Report.cshtml
@using System.Globalization
@model G3SpiritsReports.Models.ViewModels.ReportTableViewModel
@{
    ViewBag.Title = "Home Page";
}
@{
    if (Model != null)
    {

        var date = Convert.ToDateTime(Model.Date);
        var textInfo = new CultureInfo("en-US", false).TextInfo;

        <div id="header">
            <div id="header-table">
                <table>
                    <thead>
                        <tr>
                            <th class="month">@textInfo.ToTitleCase(CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName(date.Month))</th>
                            <th class="date">@Model.Date</th>
                            <th class="menu-button">@Html.ActionLink("Menu", "Index", "MonthlyBrandReport", new { }, new { @class = "button" })</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
        <div id="main" style="width:100%">
            <table style="width:100%">
                <tr>
                    <td width="75%" style="vertical-align:top;">
                        
                        <div id="main-table">
                            <table id="top-table">
                                @{
                                    if(Model.MonthlyBrandReportTables != null)
                                    { 
        var i = 0;
        foreach (var line in Model.MonthlyBrandReportTables)
        {
            if (i > 8)
            {
                continue;
            }
            string cssClassPlan;
            var cssClass = "";
            const string cssClassSum = "header";
            var cssWidth = "";
            if (i > 0)
            {
                cssClassPlan = "green";
                if (!line.OnPlan)
                {
                    cssClassPlan = "red";
                }
            }
            else
            {
                cssClassPlan = "left";
                cssClass = "left";
                cssWidth = "width:250px";
            }
            var cssClassPlanPercentage = cssClassPlan + " percentage";
            <tr>
                <td class="@cssClassSum" style="@cssWidth">@line.Name</td>
                <td class="@cssClass">@line.MonthlyPlan</td>
                <td class="@cssClass">@line.MonthlyPlanToDate</td>
                <td class="@cssClassPlan">@line.SoldPieces</td>
                <td class="@cssClassPlanPercentage">@line.SoldPercentage</td>
                <td style="position: relative; vertical-align: bottom;">
                    @{
            if (line.Image != null)
            {
                var base64 = Convert.ToBase64String(line.Image);
                var imgSrc = String.Format("data:image/png;base64,{0}", base64);
                <img src="@imgSrc" width="70" style="position: relative;" />
            }
                    }
                </td>

            </tr>
            i++;
        }
                                    }
    }
                            </table><br /><br />
                            <table id="bottom-table">
                                @{
        if (Model.MonthlyBrandReportTables != null)
        {
        var k = 0;
        foreach (var line in Model.MonthlyBrandReportTables)
        {
            if (k == 0 || k > 8)
            {
                string cssClassPlan;
                var cssClass = "";
                const string cssClassSum = "header";
                var cssWidth = "";
                if (k > 0)
                {
                    cssClassPlan = "green";
                    if (!line.OnPlan)
                    {
                        cssClassPlan = "red";
                    }
                }
                else
                {
                    cssClassPlan = "left";
                    cssClass = "left";
                    cssWidth = "width:250px";
                }
                var cssClassPlanPercentage = cssClassPlan + " percentage";
                <tr>
                    <td class="@cssClassSum" style="@cssWidth">@line.Name</td>
                    <td class="@cssClass">@line.MonthlyPlan</td>
                    <td class="@cssClass">@line.MonthlyPlanToDate</td>
                    <td class="@cssClassPlan">@line.SoldPieces</td>
                    <td class="@cssClassPlanPercentage">@line.SoldPercentage</td>
                    <td style="position: relative; vertical-align: bottom;">
                        @{
                if (line.Image != null)
                {
                    var base64 = Convert.ToBase64String(line.Image);
                    var imgSrc = String.Format("data:image/png;base64,{0}", base64);
                    <img src="@imgSrc" width="70" style="position: relative;" />
                }
                        }
                    </td>

                </tr>
            }
            k++;
        }
                                }}
                            </table>
                        </div>

                    </td>
                    <td width="25%" style="text-align: center; vertical-align: top;padding:0 1%">
                        <table>
                            <tr>
                                <td>
                                    <div id="cumulative-table">
                                        @{if (Model.MonthlyReportTable != null)
                                        {
                                            <table>
                                                <tr>
                                                    <td style="text-align: left; padding: 10px 5px 2px">Plan</td>
                                                    <td style="text-align: right; padding: 10px 5px 2px">@Model.MonthlyReportTable.MonthlyPlan€</td>
                                                </tr>
                                                <tr>
                                                    <td style="text-align: left; padding: 0 5px">Monthly Plan To Date</td>
                                                    <td style="text-align: right; padding: 0 5px;">@Model.MonthlyReportTable.MonthlyPlanToDate€</td>
                                                </tr>
                                                <tr>
                                                    <td style="text-align: left; padding: 2px 5px 10px">Achieved</td>
                                                    <td style="text-align: right; padding: 2px 5px 10px;">@Model.MonthlyReportTable.SoldValue€</td>
                                                </tr>
                                            </table>
                                        }
                                        else
                                        {
                                            <table>
                                                <tr>
                                                    <td style="text-align: left;">No Data Inserted In Monthly Report Tool<br /> For The Date Above.</td>
                                                </tr>
                                            </table>
                                        }
                                        }
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>@if (Model.YearlyBrandReportTables != null)
                                {
                                        
                                    <div id="yearly-reports">
                                        <table style="width:100%">
                                            @foreach (var item in Model.YearlyBrandReportTables)
                                            {
                                                <tr>
                                                    <td>
                                                        <div class="item">
                                                            <div class="name">@item.Name</div>
                                                            <div class="chart">
                                                                <div id="margin_@item.Name">&nbsp;</div>
                                                                @{
                                                var j = 0;
                                                var showAchievedArrow = false;

                                                <table>
                                                    @foreach (var report in item.YearlyBrandReport)
                                                    {
                                                        var soldPieces = "";
                                                        var achievedLine = "";
                                                        var plannedLine = "";
                                                        var chartLineArrow = "";
                                                        var achievedLineArrow = "";
                                                        var plannedLineArrow = "";
                                                        if (j == 0)
                                                        {
                                                            chartLineArrow = "arrow";
                                                        }
                                                        if (report.SoldPieces > 0)
                                                        {
                                                            soldPieces = report.SoldPieces.ToString(CultureInfo.InvariantCulture);
                                                            achievedLine = "achieved-line";
                                                            plannedLine = "chart-line-planned";

                                                        }
                                                        if (report.SoldPieces > 0 && !showAchievedArrow)
                                                        {
                                                            showAchievedArrow = true;
                                                            achievedLineArrow = "arrow";
                                                            plannedLineArrow = "arrow";
                                                        }
                                                        <tr class="line">
                                                            <td class="month">@textInfo.ToTitleCase(CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName(report.Month))</td>
                                                            <td class="planned-pieces">@report.PlannedPieces</td>
                                                            <td class="chart-line @chartLineArrow @plannedLine @plannedLineArrow">&nbsp;</td>
                                                            <td class="@achievedLine @achievedLineArrow">&nbsp;</td>
                                                            <td class="sold-pieces">@soldPieces</td>
                                                        </tr>
                                                        j++;
                                                    }
                                                </table>
                                                                    <div class="yearly-planned-ammount">&nbsp;</div>
                                                                    <div class="yearly-planned-ammount-value">@item.YearlyPiecesSum</div>
                                                                    <div class="monthly-planned-ammount">&nbsp;</div>
                                                                    <div class="monthly-planned-ammount-value">@item.PlannedPiecesSum</div>
                                                                    <div class="monthly-achieved-ammount">&nbsp;</div>
                                                                    <div class="monthly-achieved-ammount-value">@item.AchievedPiecesSum</div>


                                                                }
                                                            </div>
                                                            <div class="clear" style="clear: both;"></div>
                                                        </div>
                                                        <div class="clear" style="clear: both;"></div>
                                                    </td>
                                                </tr>
                                            }
                                        </table>
                                    </div>

                                }</td>
                            </tr>
                        </table>
                        


                        
                    </td>
                </tr>
            </table>




        </div>
        @section Scripts {
            @Scripts.Render("~/bundles/home/report")
        }
    }
    else
    {
        <div>There is something  wrong with the data!</div>
    }
    <div style="clear:both;"></div>
}