G3SpiritsReports.UI/Controllers/BrandController.cs
using G3SpiritsReports.BusinessLogic.Brands;
using G3SpiritsReports.Models.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace G3SpiritsReports.UI.Controllers
{
    [Authorize]
    public class BrandController : Controller
    {
        private readonly BrandManager _brandManager = new BrandManager();
        //
        // GET: /Brand/

        public ActionResult Index()
        {
            var brands = _brandManager.GetAllBrands();
            return View(brands);
        }

        //
        // GET: /Brand/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Brand/Create

        [HttpPost]
        public ActionResult Create(Brand brand)
        {
            try
            {
                _brandManager.CreateBrand(brand);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Brand/Edit/5

        public ActionResult Edit(int brandId)
        {
            var brand = _brandManager.GetBrand(brandId);
            return View(brand);
        }

        //
        // POST: /Brand/Edit/5

        [HttpPost]
        public ActionResult Edit(Brand brand, HttpPostedFileBase file)
        {
            try
            {
                byte[] image = null;
                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    string path;
                    if (fileName != null)
                    {
                        path = Path.Combine(Server.MapPath("~/App_Data"), fileName);
                        file.SaveAs(path);
                        image = System.IO.File.ReadAllBytes(path);
                        System.IO.File.Delete(path);
                    }

                }
                _brandManager.EditBrand(brand, image);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public string SaveSort(int brandId, int sortOrder)
        {
            try
            {
                _brandManager.SaveSort(brandId, sortOrder);
                return "OK";
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }
    }
}

G3SpiritsReports.UI/Controllers/CountryController.cs
using G3SpiritsReports.BusinessLogic.Countries;
using G3SpiritsReports.Models.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace G3SpiritsReports.UI.Controllers
{
    [Authorize]
    public class CountryController : Controller
    {
        private readonly CountryManager _countryManager = new CountryManager();
        //
        // GET: /Country/

        public ActionResult Index()
        {
            var countries = _countryManager.GetAllCountries();
            return View(countries);
        }

        //
        // GET: /Brand/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Brand/Create

        [HttpPost]
        public ActionResult Create(Country country)
        {
            try
            {
                _countryManager.CreateCountry(country);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Brand/Edit/5

        public ActionResult Edit(int countryId)
        {
            var country = _countryManager.GetCountry(countryId);
            return View(country);
        }

        //
        // POST: /Brand/Edit/5

        [HttpPost]
        public ActionResult Edit(Country country)
        {
            try
            {
                _countryManager.EditCountry(country);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

G3SpiritsReports.UI/Controllers/MonthlyReportController.cs
using G3SpiritsReports.BusinessLogic.MonthlyReports;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace G3SpiritsReports.UI.Controllers
{
    [Authorize]
    public class MonthlyReportController : Controller
    {
        //
        // GET: /MonthlyReport/
        private readonly MonthlyReportManager _monthlyReportManager = new MonthlyReportManager();
        public ActionResult Index()
        {
            var countryId = Convert.ToInt32(Request.QueryString["countryId"]);
            if (countryId == 0)
            {
                countryId = 1;
            }
            var month = Convert.ToInt32(Request.QueryString["month"]);
            if (month == 0)
            {
                month = DateTime.Now.Month;
            }
            var year = Convert.ToInt32(Request.QueryString["year"]);
            if (year == 0)
            {
                year = DateTime.Now.Year;
            }
            var monthlyReportViewModel = _monthlyReportManager.GetMonthlyReport(countryId, month, year);
            return View(monthlyReportViewModel);
        }

        [HttpGet]
        public string CreateOrEdit(int countryId, int month, int year, decimal plannedValue, decimal soldValue)
        {
            try
            {
                _monthlyReportManager.CreateOrEdit(countryId, month, year, plannedValue, soldValue);
                return "OK";
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }
    }
}

G3SpiritsReports.UI/Controllers/YearlyBrandReportController.cs
using G3SpiritsReports.BusinessLogic.YearlyBrandReports;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace G3SpiritsReports.UI.Controllers
{
    [Authorize]
    public class YearlyBrandReportController : Controller
    {
        private readonly YearlyBrandReportManager _yearlyBrandReportManager = new YearlyBrandReportManager();
        //
        // GET: /YearlyBrandReport/

        public ActionResult Index()
        {
            var countryId = Convert.ToInt32(Request.QueryString["countryId"]);
            if (countryId == 0)
            {
                countryId = 1;
            }
            var brandId = Convert.ToInt32(Request.QueryString["brandId"]);
            if (brandId == 0)
            {
                brandId = 1;
            }
            var year = Convert.ToInt32(Request.QueryString["year"]);
            if (year == 0)
            {
                year = DateTime.Now.Year;
            }
            var yearlyBrandReportViewModel = _yearlyBrandReportManager.GetYearlyBrandReportViewModel(countryId, brandId, year);
            return View(yearlyBrandReportViewModel);
        }

        [HttpGet]
        public string CreateOrEdit(int countryId, int brandId, int year, int month, int plannedPieces, int soldPieces)
        {
            try
            {
                _yearlyBrandReportManager.CreateOrEdit(countryId, brandId, year, month, plannedPieces, soldPieces);
                return "OK";
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }
    }
}

G3SpiritsReports.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET MVC Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/themes/base/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">@Html.ActionLink("G3Spirits Reports", "Index", "Home")</p>
            </div>
            <div class="float-right">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
                <nav>
                    <ul id="menu">
                        <li>&nbsp;</li>
                        @if (Request.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("Tables", "Index", "Home")</li>
                            <li>@Html.ActionLink("DailyReports", "Index", "MonthlyBrandReport")</li>
                            <li>@Html.ActionLink("MonthlyPlans", "Index", "MonthlyBRandPlan")</li>
                            <li>@Html.ActionLink("MonthlyReports", "Index", "MonthlyReport")</li>
                            <li>@Html.ActionLink("YearlyBrandReports", "Index", "YearlyBrandReport")</li>
                            <li>@Html.ActionLink("Brands", "Index", "Brand")</li>
                            <li>@Html.ActionLink("Countries", "Index", "Country")</li>
                            <li>@Html.ActionLink("Users", "Index", "Account")</li>
                        }
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - Soft.si, All Rights Reserved.</p>
            </div>
        </div>
    </footer>

    @RenderSection("scripts", required: false)
</body>
</html>

G3SpiritsReports.UI/Views/Shared/_ReportLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET MVC Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
</head>
<body class="no-background">
    <div style="text-align: center;">
        @RenderBody()
        @RenderSection("scripts", required: false)
    </div>
</body>
</html>